### ISSUE TITLE
Discussion with wpengine

### ISSUE THREAD

**Issue by KLVTZ** [schrapel/wpengine-bedrock-build#1]
Nice script, something similar was implemented:
- https://github.com/mehtryx/wpengine-deploy

But you did an extra step and added Bedrock --thanks!

But this leaves me to question, did you ever reach out to wpengine and asked them to change the document root? Would they do this for? I want to implement bedrock in our next project and was curious how flexible they where?

**Comment by KLVTZ** [comment]
Also, how do you handle composer vendor folder dependencies?

**Comment by KLVTZ** [comment]
@schrapel called wpengine. Gave me the roundabout on defining a custom document root. They are not going to support it. Sure they'll allow you to change whatever you want in your git env. or just sftp. But the minute you mention document root change, they are not happy. Their primary reason behind this is that they have certain tools for backup, environment variables define in config, and other stuff setup for their environment. So I understand that there is an added complexity to include all this on production. But to completely not support this flexibility is disappointing. Oh well, this is a good alternative!

**Comment by schrapel** [comment]
The composer folder will just be committed like anything else.

I was already aware WPEngine wouldn't support WP in another folder hence why I made the script. However, now I've moved away from WPEngine and really only use https://github.com/carlalexander/debops-wordpress on Digital Ocean.

**Comment by KLVTZ** [comment]
Ahh okay. I'm new to wpengine and the above info wasn't clear to me until you start digging into what they actually offer. Good for you for moving! I wish we could :(
