### ISSUE TITLE
[feature request] Compile blade templates during build process

### ISSUE THREAD

**Issue by kyle-mccarthy** [schrapel/wpengine-bedrock-build#2]
Is it possible for you to add a feature that would compile blade templates during the build process? The way that the hashes for the cached blade files are generated involves using the path to the template file, which fails once deployed to wpengine.

**Comment by schrapel** [comment]
@kyle-mccarthy I am sorry. I did not see this before. Check out my blog post on how I achieved this.

https://tobyschrapel.com/deploying-sage-9-blade-templates-to-wp-engine-using-gitlab-ci-pipelines/
